// components/ui/label.tsx
import type { VariantProps } from 'class-variance-authority';
import { cva } from 'class-variance-authority';
import { Label as LabelPrimitives } from 'radix-ui';
import type { ComponentProps } from 'react';
import { cn } from '@/lib/cn';

export type LabelProps = ComponentProps<typeof LabelPrimitives.Root> &
  VariantProps<typeof labelVariants>;

export const labelVariants = cva(
  'font-medium text-neutral-100 text-sm leading-none peer-disabled:cursor-not-allowed',
  {
    variants: {
      position: {
        inset: 'absolute top-3 left-4 z-50 text-xs transition-all',
      },
      variant: {
        error: 'text-error-500',
      },
    },
  }
);

export function Label({
  className,
  variant,
  position,
  ref,
  ...props
}: LabelProps) {
  return (
    <LabelPrimitives.Root
      className={cn(
        labelVariants({
          className,
          position,
          variant,
        })
      )}
      ref={ref}
      {...props}
    />
  );
}
Label.displayName = LabelPrimitives.Root.displayName;

// src/lib/components/label/label.svelte
<script lang="ts">
  import { Label } from "bits-ui";
  import { cva, type VariantProps } from "class-variance-authority";

  type LabelProps = Label.RootProps & VariantProps<typeof labelVariants>;

  export const labelVariants = cva("label", {
    variants: {
      size: {
        large: "label--large",
        medium: "label--medium",
        small: "label--small",
      },
    },
    defaultVariants: {
      size: "medium",
    },
  });

  let {
    ref = $bindable(null),
    class: className,
    size,
    ...props
  }: LabelProps = $props();
</script>

<Label.Root bind:ref class={labelVariants({ size, className })} {...props} />

<style>
  :global {
    @layer components {
      .label {
        color: var(--color-neutral-12);
        font-weight: 500;
        line-height: 1.375;
        letter-spacing: normal;
      }

      .label--large {
        font-size: var(--text-label-large);
      }

      .label--medium {
        font-size: var(--text-label-medium, 0.875rem);
      }

      .label--small {
        font-size: var(--text-label-small, 0.75rem);
      }
    }
  }
</style>
